### ISSUE TITLE
Notifications on IOS 8 and 9 don't disappear

### ISSUE THREAD

**Issue by Drenaz** [etienne-martin/jquery.dialog.js#1]
There is an issue affecting most iPhone 5 to 6 and most iPads.

The issue happens after clicking / confirming a notification. The pop up box disappears but the screen remains darkened and user cannot click on any elements on the page.

Here is a video using BrowserStack and testing on the demo page.
https://drive.google.com/file/d/0B83BCuMeKK1KbFN6UnNqcUlpYzA/view?usp=sharing

**Comment by etienne-martin** [comment]
Thanks for the report (and the video).

The demonstration page to which you refer is not maintained by me. It's not up to date either.

Try with the official demo page to see if the problem persists: https://codepen.io/etiennemartin/full/mWVWEQ/

**Comment by Drenaz** [comment]
Hi, I've tested on this your official page and the problem persists. Also the pop up does not show up unless you scroll down half way. Seems iOS does not want to play nicely.

Here another test video for iPhone / iPad
https://drive.google.com/file/d/0B83BCuMeKK1KaVMzalR6OVFvWjQ/view?usp=sharing

Here is a working example with Android
https://drive.google.com/file/d/0B83BCuMeKK1KdWltQjM1bnNtRGM/view?usp=sharing

Thanks

**Comment by etienne-martin** [comment]
Thanks for the update. 

I've been able to reproduce the issue on iOS 8 & 9. 

~I'll be fixed as soon as possible.~

Thanks again.
