### ISSUE TITLE
[Closed - Not Solved ] Form -  Submit Button - Replace Standard "onclick=return confirm()" box

### ISSUE THREAD

**Issue by marcoczen** [etienne-martin/jquery.dialog.js#2]
Hi,

I currently have a bootstrap form as below;

         <form action="action.php?goto=viewusers" method="post" id="form_viewuser_userlisting">
             // some fields
         </form>

And submit button ( 3 submit buttons actually ,one for add, one for delete, one for edit )

    <button type="submit" class="btn btn-primary" name="button_deluser"  
       onclick="return confirm('Delete User ? Confirm Proceed ?');" > Delete Selected User 
    </button>

The above works fine. When the button is clicked, i get a standard javascript popup box which if i select OK, submits the form and the action is done.

Now I would like to get a better looking popup box and hence i have come to your plugin.
Some questions;

A1. 

    dialog.confirm({
	    message: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
	    callback: function(response){
		    console.log(response); 
	    }
    });

What is the code to replace console.log(response)  to submit the form if user clicks YES in the        
popup box after the submit button is clicked ?

Or do i just do edit the button and add 

     onclick="return dialog.confirm('Delete User ? Confirm Proceed ?');"

A2. Do i wrap the above in a $document ready ? or is that not necessary ?

    $(document).ready(function() { */
        // put A1 here ?
     }); 

A3. Can i put A2 into an external js file , say into my header.php ( which includes my <!DOCTYPE html> , <html lang="en">  and <head> tags.

B1. What do i have to do the form tag and / or the button to get this better looking javascript confirmation popup box ?

Thanks.
p.s - Jquery newbie here.

**Comment by etienne-martin** [comment]
The document.ready event is not necessary.

Your form:

```
<form action="action.php?goto=viewusers" method="post" id="form_viewuser_userlisting">
    <button type="submit" class="btn btn-primary" name="button_deluser">Delete Selected User</button>
</form>
```

Your JS:

```
$("#form_viewuser_userlisting").submit(function(){
    dialog.confirm({ 
        message: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 
        callback: function(response){ 
            if(response){ 
              	$('#form_viewuser_userlisting')[0].submit() 
            } 
        }
    })
    return false
})
```

You can put the JS in an external file.

**Comment by marcoczen** [comment]
Roger that. Testing.

**Comment by marcoczen** [comment]
Hi @etienne-martin ,

I tried your code snippet above. Feedback below.

Good Part:

The jquery confirmation box appeared !
:)

Hmmmm Part:

After clicking YES - form is submitted to the same page ( as per design ) but the next form ( edit form ) does not appear.  Checked and found that submit button name was not getting sent along as a post variable.

I tried using the button click event as below ( attaching to the submit button with id = "confirm_edit" but the button name is still not being sent.

      $("#confirm_edit").click(function(){
		     dialog.confirm({
                           title: "Edit ? Proceed ?",
                           button: "YES - Proceed !",
                           cancel: "NO - Cancel !",
                                required: true,
                                     callback: function(response){
                                           if (response){                    
                                             $("#form_root_viewuser_userlisting")[0].submit();   
                                           }
                          }
		});

		return false;

       });

I know the overall form is submitting - because a flag message pops out in the apache log due to a mysqli operation but since the submit button  is not being sent along with the rest of the form data, the next step is bungled.

This is the current submit button code;

    <button type="submit" class="btn btn-primary" name="button_edituser"  
     id="confirm_edit" > Edit Selected User 
    </button>

I understand that this due to some DOM/Jquery issue but is there any way i can pass along the name of the button( along with value if available)  along with the formdata so that code like ;

      if ( isset($_POST['button_edituser'])) { // after  button " Edit Selected User " clicked

will work ?

**Comment by etienne-martin** [comment]
For questions that are not related to jquery.dialog.js, please post them on [stackoverflow.com](https://stackoverflow.com/).

Send me the link to your question here and I'll take a look at it.

**Comment by marcoczen** [comment]
Roger. Thanks.

**Comment by marcoczen** [comment]
Update - after reading up on the DOM/Jquery issue on buttons and forms , that issue seems to be related to when buttons have names "submit". 

From https://api.jquery.com/submit/

"Forms and their child elements should not use input names or ids that conflict with properties of a form, such as submit, length, or method. Name conflicts can cause confusing failures. For a complete list of rules and to check your markup for these problems"

In my case, the buttons all have other names like adduser, edituser etc.

So any idea why jquery dialog is not able to submit forms in the callback function ?
Is there a working example where jquery.dialog actually submits a form - is there some jsfiddle ?

**Comment by etienne-martin** [comment]
For questions that are not related to jquery.dialog.js, please post them on [stackoverflow.com](https://stackoverflow.com/).

Send me the link to your question here and I'll take a look at it.

**Comment by tpaksu** [comment]
There's an easy solution for this:

**The form**
```
<form action="action.php?goto=viewusers" method="post" id="form_viewuser_userlisting" onsubmit='return deleteuser(this)'>
    <button type="submit" class="btn btn-primary" name="button_deluser">Delete Selected User</button>
</form>
```

**The script**:
```
 var deleteuser = function (form) {
    dialog.confirm({
        title: "Confirm Deletion",
        message: "Are you sure you want to delete this user?",
        callback: function (response) {
            if(response){
                $(form).removeAttr("onsubmit").submit();
            }
        }
    });
    return false;
};
```
